# Generated by Django 4.0.3 on 2022-04-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.CharField(max_length=255, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='utility_bill',
            field=models.CharField(max_length=120, verbose_name='Current Utility Bill'),
        ),
    ]
